In [91]:
# load necessary libraries
import pandas as pd
import pprint
import os
# import glob

In [92]:
# import csvs
paris_csv = "/Users/AttiasC16/Desktop/Paris.csv"
bangkok_csv = "/Users/AttiasC16/Desktop/Bangkok.csv"
newyork_csv = "/Users/AttiasC16/Desktop/NewYork.csv"
london_csv = "/Users/AttiasC16/Desktop/London.csv"
hongkong_csv = "/Users/AttiasC16/Desktop/HongKong.csv"
singapore_csv = "/Users/AttiasC16/Desktop/Singapore.csv"
instanbul_csv = "/Users/AttiasC16/Desktop/Instanbul.csv"

In [93]:
# read csv into pandas df
paris_df = pd.read_csv(paris_csv)
bangkok_df = pd.read_csv(bangkok_csv)
newyork_df = pd.read_csv(newyork_csv)
london_df = pd.read_csv(london_csv)
hongkong_df = pd.read_csv(hongkong_csv)
singapore_df = pd.read_csv(singapore_csv)
instanbul_df = pd.read_csv(instanbul_csv)

/var/folders/s8/06x09z5j12g_t79tbrhn448w0000gn/T/ipykernel_3210/3865770108.py:4: DtypeWarning: Columns (68) have mixed types. Specify dtype option on import or set low_memory=False.
  newyork_df = pd.read_csv(newyork_csv)

In [94]:
# add "city" column to each df 
paris_df["city"] = "paris"
bangkok_df["city"] = "bangkok"
newyork_df["city"] = "newyork"
london_df["city"] = "london"
hongkong_df["city"] = "hongkong"
singapore_df["city"] = "singapore"
instanbul_df["city"] = "instanbul"

In [114]:
# count number of rows in each df
paris_length = len(paris_df["id"])
bangkok_length = len(bangkok_df["id"])
newyork_length = len(newyork_df["id"])
london_length = len(london_df["id"])
hongkong_length = len(hongkong_df["id"])
singapore_length = len(singapore_df["id"])
instanbul_length = len(instanbul_df["id"])
print(f"paris length: {paris_length}")
print(f"bangkok length: {bangkok_length}")
print(f"newyork length: {newyork_length}")
print(f"london length: {london_length}")
print(f"hongkong length: {hongkong_length}")
print(f"singapore length: {singapore_length}")
print(f"instanbul length: {instanbul_length}")

paris length: 55104
bangkok length: 15854
newyork length: 41533
london length: 71938
hongkong length: 5194
singapore length: 3037
instanbul length: 36717

In [96]:
# find length of all dfs (make sure it matches merged_df)
combined_length = paris_length + bangkok_length + newyork_length + london_length + hongkong_length + singapore_length + instanbul_length
combined_length

229377

In [98]:
# display dataframe 
#paris_df.head()
#bangkok_df.head()
#newyork_df.head()
#london_df.head()
#hongkong_df.head()
#singapore_df.head()
#instanbul_df.head()

In [99]:
# look at headers
#paris_df.columns 
for x in paris_df.columns: 
    print(x)

id
listing_url
scrape_id
last_scraped
source
name
description
neighborhood_overview
picture_url
host_id
host_url
host_name
host_since
host_location
host_about
host_response_time
host_response_rate
host_acceptance_rate
host_is_superhost
host_thumbnail_url
host_picture_url
host_neighbourhood
host_listings_count
host_total_listings_count
host_verifications
host_has_profile_pic
host_identity_verified
neighbourhood
neighbourhood_cleansed
neighbourhood_group_cleansed
latitude
longitude
property_type
room_type
accommodates
bathrooms
bathrooms_text
bedrooms
beds
amenities
price
minimum_nights
maximum_nights
minimum_minimum_nights
maximum_minimum_nights
minimum_maximum_nights
maximum_maximum_nights
minimum_nights_avg_ntm
maximum_nights_avg_ntm
calendar_updated
has_availability
availability_30
availability_60
availability_90
availability_365
calendar_last_scraped
number_of_reviews
number_of_reviews_ltm
number_of_reviews_l30d
first_review
last_review
review_scores_rating
review_scores_accuracy
review_scores_cleanliness
review_scores_checkin
review_scores_communication
review_scores_location
review_scores_value
license
instant_bookable
calculated_host_listings_count
calculated_host_listings_count_entire_homes
calculated_host_listings_count_private_rooms
calculated_host_listings_count_shared_rooms
reviews_per_month
city

In [100]:
# merge into one df
merged_df = pd.concat([paris_df, bangkok_df, newyork_df, london_df, hongkong_df, singapore_df, instanbul_df])
merged_df.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,city
0,5396.0,https://www.airbnb.com/rooms/5396,2.022120e+13,12/11/22,city scrape,Explore the heart of old Paris,"Cozy, well-appointed and graciously designed s...","You are within walking distance to the Louvre,...",https://a0.muscache.com/pictures/52413/f9bf76f...,7903,...,4.95,4.55,7.5104E+12,f,1,1,0,0,1.98,paris
1,7397.0,https://www.airbnb.com/rooms/7397,2.022120e+13,12/11/22,city scrape,MARAIS - 2ROOMS APT - 2/4 PEOPLE,"VERY CONVENIENT, WITH THE BEST LOCATION !<br /...",NaN,https://a0.muscache.com/pictures/67928287/330b...,2626,...,4.93,4.72,7.5104E+12,f,2,2,0,0,2.26,paris
2,7964.0,https://www.airbnb.com/rooms/7964,2.022120e+13,12/11/22,previous scrape,Large & sunny flat with balcony !,Very large & nice apartment all for you! <br /...,NaN,https://a0.muscache.com/pictures/4471349/6fb3d...,22155,...,5.00,5.00,7.5109E+12,f,1,1,0,0,0.04,paris
3,9359.0,https://www.airbnb.com/rooms/9359,2.022120e+13,12/11/22,city scrape,"Cozy, Central Paris: WALK or VELIB EVERYWHERE !",Location! Location! Location! Just bring your ...,NaN,https://a0.muscache.com/pictures/c2965945-061f...,28422,...,NaN,NaN,"Available with a mobility lease only (""bail mo...",f,1,1,0,0,NaN,paris
4,81870.0,https://www.airbnb.com/rooms/81870,2.022120e+13,12/11/22,previous scrape,Saint Germain Musee d'orsay,<b>The space</b><br />This beautiful apartment...,NaN,https://a0.muscache.com/pictures/558458/3c1263...,152242,...,5.00,4.00,NaN,f,78,78,0,0,0.01,paris

In [101]:
### IF merging csv files 
# list all csv files only
#csv_files = glob.glob('*.{}'.format('csv'))
#csv_files
# merge files 
#merged_df = pd.concat([pd.read_csv(x) for x in csv_files ], ignore_index=True)
#merged_df.head()

In [102]:
# count number of rows to make sure all merged
merged_length = len(merged_df["id"]) 
merged_length

229377

In [103]:
# look at columns 
for x in merged_df.columns: 
    print(x)

id
listing_url
scrape_id
last_scraped
source
name
description
neighborhood_overview
picture_url
host_id
host_url
host_name
host_since
host_location
host_about
host_response_time
host_response_rate
host_acceptance_rate
host_is_superhost
host_thumbnail_url
host_picture_url
host_neighbourhood
host_listings_count
host_total_listings_count
host_verifications
host_has_profile_pic
host_identity_verified
neighbourhood
neighbourhood_cleansed
neighbourhood_group_cleansed
latitude
longitude
property_type
room_type
accommodates
bathrooms
bathrooms_text
bedrooms
beds
amenities
price
minimum_nights
maximum_nights
minimum_minimum_nights
maximum_minimum_nights
minimum_maximum_nights
maximum_maximum_nights
minimum_nights_avg_ntm
maximum_nights_avg_ntm
calendar_updated
has_availability
availability_30
availability_60
availability_90
availability_365
calendar_last_scraped
number_of_reviews
number_of_reviews_ltm
number_of_reviews_l30d
first_review
last_review
review_scores_rating
review_scores_accuracy
review_scores_cleanliness
review_scores_checkin
review_scores_communication
review_scores_location
review_scores_value
license
instant_bookable
calculated_host_listings_count
calculated_host_listings_count_entire_homes
calculated_host_listings_count_private_rooms
calculated_host_listings_count_shared_rooms
reviews_per_month
city

In [104]:
# delete columns not needed 
delete_columns_df = merged_df.drop(['scrape_id', 'last_scraped', 'source', 'host_id', 'host_url', 'host_location', 'host_about', 
                'host_response_time', 'host_acceptance_rate', 'host_thumbnail_url', 'host_picture_url', 'host_neighbourhood', 
                'host_total_listings_count', 'host_verifications', 'host_has_profile_pic', 'host_identity_verified', 
                'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'bathrooms', 'minimum_minimum_nights', 
                'maximum_minimum_nights', 'minimum_maximum_nights', 'maximum_maximum_nights', 'minimum_nights_avg_ntm',
                'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability', 'availability_30', 'availability_60',
                'availability_90', 'availability_365', 'calendar_last_scraped', 'number_of_reviews', 'number_of_reviews_ltm', 
                'number_of_reviews_l30d', 'first_review', 'last_review', 'review_scores_accuracy', 'review_scores_checkin', 
                'review_scores_location', 'review_scores_value', 'license', 'instant_bookable', 'calculated_host_listings_count', 
               'calculated_host_listings_count_entire_homes', 'calculated_host_listings_count_private_rooms', 
                'calculated_host_listings_count_shared_rooms', 'reviews_per_month', 'neighborhood_overview', 
                'minimum_nights', 'maximum_nights'], axis=1)
delete_columns_df.head()

,id,listing_url,name,description,picture_url,host_name,host_since,host_response_rate,host_is_superhost,host_listings_count,...,accommodates,bathrooms_text,bedrooms,beds,amenities,price,review_scores_rating,review_scores_cleanliness,review_scores_communication,city
0,5396.0,https://www.airbnb.com/rooms/5396,Explore the heart of old Paris,"Cozy, well-appointed and graciously designed s...",https://a0.muscache.com/pictures/52413/f9bf76f...,Borzou,2/14/09,100%,f,1.0,...,2,1 bath,NaN,1.0,"[""Cleaning products"", ""Oven"", ""Host greets you...",$93.00,4.55,4.51,4.82,paris
1,7397.0,https://www.airbnb.com/rooms/7397,MARAIS - 2ROOMS APT - 2/4 PEOPLE,"VERY CONVENIENT, WITH THE BEST LOCATION !<br /...",https://a0.muscache.com/pictures/67928287/330b...,Franck,8/30/08,100%,t,2.0,...,4,1 bath,2.0,2.0,"[""Free washer \u2013 In unit"", ""Oven"", ""Host g...",$119.00,4.72,4.43,4.88,paris
2,7964.0,https://www.airbnb.com/rooms/7964,Large & sunny flat with balcony !,Very large & nice apartment all for you! <br /...,https://a0.muscache.com/pictures/4471349/6fb3d...,Anaïs,6/18/09,NaN,f,1.0,...,2,1 bath,1.0,1.0,"[""Cleaning products"", ""Free washer \u2013 In u...",$130.00,4.80,5.00,5.00,paris
3,9359.0,https://www.airbnb.com/rooms/9359,"Cozy, Central Paris: WALK or VELIB EVERYWHERE !",Location! Location! Location! Just bring your ...,https://a0.muscache.com/pictures/c2965945-061f...,Bernadette,7/29/09,NaN,f,2.0,...,1,1 bath,1.0,1.0,"[""Long term stays allowed"", ""Dedicated workspa...",$75.00,NaN,NaN,NaN,paris
4,81870.0,https://www.airbnb.com/rooms/81870,Saint Germain Musee d'orsay,<b>The space</b><br />This beautiful apartment...,https://a0.muscache.com/pictures/558458/3c1263...,Delphine,6/25/10,59%,f,86.0,...,2,1 bath,1.0,1.0,"[""Oven"", ""Host greets you"", ""Coffee maker"", ""C...",$145.00,5.00,5.00,5.00,paris

In [105]:
# look at columns 
for x in delete_columns_df.columns: 
    print(x)

id
listing_url
name
description
picture_url
host_name
host_since
host_response_rate
host_is_superhost
host_listings_count
neighbourhood
latitude
longitude
property_type
room_type
accommodates
bathrooms_text
bedrooms
beds
amenities
price
review_scores_rating
review_scores_cleanliness
review_scores_communication
city

In [108]:
# remove any rows containing n/a
cleaned_df = delete_columns_df.dropna()
cleaned_df.head()

,id,listing_url,name,description,picture_url,host_name,host_since,host_response_rate,host_is_superhost,host_listings_count,...,accommodates,bathrooms_text,bedrooms,beds,amenities,price,review_scores_rating,review_scores_cleanliness,review_scores_communication,city
5,9952.0,https://www.airbnb.com/rooms/9952,Paris petit coin douillet,"Je suis une dame retraitée, qui propose un agr...",https://a0.muscache.com/pictures/ae822d16-74d2...,Elisabeth,8/24/09,100%,t,1.0,...,2,1 bath,1.0,1.0,"[""Oven"", ""Host greets you"", ""Coffee maker"", ""S...",$140.00,4.91,4.86,4.84,paris
6,84820.0,https://www.airbnb.com/rooms/84820,Bird's nest in Montmartre: Sun/view all over P...,"Apartment, two rooms, very calm and sunny.<br ...",https://a0.muscache.com/pictures/581023/86105d...,Laure,3/26/11,100%,t,1.0,...,3,1.5 baths,1.0,1.0,"[""Free washer \u2013 In unit"", ""Oven"", ""Host g...",$83.00,4.87,4.86,4.88,paris
10,86053.0,https://www.airbnb.com/rooms/86053,Charmful flat facing a gothic church,Amazing apartment totally renovated facing one...,https://a0.muscache.com/pictures/1982057/f94cf...,Richard,11/23/10,100%,t,1.0,...,4,1 bath,1.0,2.0,"[""Baking sheet"", ""Children\u2019s books and to...",$268.00,4.87,4.76,4.95,paris
23,11798.0,https://www.airbnb.com/rooms/11798,Loft very charming in Paris,Mon appartement est situé dans une très jolie ...,https://a0.muscache.com/pictures/22458692/09eb...,Laurence,10/8/09,100%,f,1.0,...,2,1 bath,1.0,1.0,"[""Oven"", ""Host greets you"", ""Coffee maker"", ""S...",$130.00,4.85,4.82,4.95,paris
25,94270.0,https://www.airbnb.com/rooms/94270,Artist's atelier in Montparnasse,Charming artist's atelier turned into a spacio...,https://a0.muscache.com/pictures/3155777/980bb...,Guglielmo,11/1/10,100%,t,34.0,...,4,1 bath,2.0,3.0,"[""Ethernet connection"", ""Oven"", ""Host greets y...",$149.00,4.74,4.71,4.93,paris

In [109]:
# count how many rows left after dropna
len(cleaned_df["id"])

62663

In [110]:
# count how many listings each city has
cleaned_df["city"].value_counts()

london       20943
paris        13435
newyork      12436
instanbul     8972
bangkok       5065
hongkong       916
singapore      896
Name: city, dtype: int64

In [ ]:
# rename?????

In [ ]:
# convert price to USD
 
# conversion rate (as of 2023-03-30)

    # London (pounds) 1 pound = 1.24 usd
    # Paris (euro) 1 euro = 1.09 usd
    # Instanbul (lira) 1 lira = 0.052 usd
    # Bangkok (thai baht) 1 thai baht = 0.029 usd
    # Hong Kong (hong kong dollar) 1 hong kong dollar = 0.13 usd
    # Singapore (singapore dollar) 1 singapore dollar = 0.75 usd

In [131]:
cleaned_df['price'] = cleaned_df['price'].str.replace(',', '').str.replace('$', '')

/var/folders/s8/06x09z5j12g_t79tbrhn448w0000gn/T/ipykernel_3210/1755626730.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  cleaned_df['price'] = cleaned_df['price'].str.replace(',', '').str.replace('$', '')
/var/folders/s8/06x09z5j12g_t79tbrhn448w0000gn/T/ipykernel_3210/1755626730.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleaned_df['price'] = cleaned_df['price'].str.replace(',', '').str.replace('$', '')

In [132]:
cleaned_df['price'] = pd.to_numeric(cleaned_df['price'])

/var/folders/s8/06x09z5j12g_t79tbrhn448w0000gn/T/ipykernel_3210/66778867.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleaned_df['price'] = pd.to_numeric(cleaned_df['price'])

In [158]:
cleaned_df.head()

,id,listing_url,name,description,picture_url,host_name,host_since,host_response_rate,host_is_superhost,host_listings_count,...,bathrooms_text,bedrooms,beds,amenities,price,review_scores_rating,review_scores_cleanliness,review_scores_communication,city,USD_price
5,9952.0,https://www.airbnb.com/rooms/9952,Paris petit coin douillet,"Je suis une dame retraitée, qui propose un agr...",https://a0.muscache.com/pictures/ae822d16-74d2...,Elisabeth,8/24/09,100%,t,1.0,...,1 bath,1.0,1.0,"[""Oven"", ""Host greets you"", ""Coffee maker"", ""S...",140.0,4.91,4.86,4.84,paris,
6,84820.0,https://www.airbnb.com/rooms/84820,Bird's nest in Montmartre: Sun/view all over P...,"Apartment, two rooms, very calm and sunny.<br ...",https://a0.muscache.com/pictures/581023/86105d...,Laure,3/26/11,100%,t,1.0,...,1.5 baths,1.0,1.0,"[""Free washer \u2013 In unit"", ""Oven"", ""Host g...",83.0,4.87,4.86,4.88,paris,
10,86053.0,https://www.airbnb.com/rooms/86053,Charmful flat facing a gothic church,Amazing apartment totally renovated facing one...,https://a0.muscache.com/pictures/1982057/f94cf...,Richard,11/23/10,100%,t,1.0,...,1 bath,1.0,2.0,"[""Baking sheet"", ""Children\u2019s books and to...",268.0,4.87,4.76,4.95,paris,
23,11798.0,https://www.airbnb.com/rooms/11798,Loft very charming in Paris,Mon appartement est situé dans une très jolie ...,https://a0.muscache.com/pictures/22458692/09eb...,Laurence,10/8/09,100%,f,1.0,...,1 bath,1.0,1.0,"[""Oven"", ""Host greets you"", ""Coffee maker"", ""S...",130.0,4.85,4.82,4.95,paris,
25,94270.0,https://www.airbnb.com/rooms/94270,Artist's atelier in Montparnasse,Charming artist's atelier turned into a spacio...,https://a0.muscache.com/pictures/3155777/980bb...,Guglielmo,11/1/10,100%,t,34.0,...,1 bath,2.0,3.0,"[""Ethernet connection"", ""Oven"", ""Host greets y...",149.0,4.74,4.71,4.93,paris,

In [145]:
# create column to hold USD prices
cleaned_df["USD_price"] = ""

/var/folders/s8/06x09z5j12g_t79tbrhn448w0000gn/T/ipykernel_3210/584226323.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleaned_df["USD_price"] = ""

In [157]:
# london price
london_price = cleaned_df.loc[cleaned_df["city"] == "london"]["price"]
london_usd = london_price*1.24

# paris price 
paris_price = cleaned_df.loc[cleaned_df["city"] == "paris"]["price"]
paris_usd = paris_price*1.09

# instanbul price 
instanbul_price = cleaned_df.loc[cleaned_df["city"] == "instanbul"]["price"]
instanbul_usd = instanbul_price*0.052

# bangkok price 
bangkok_price = cleaned_df.loc[cleaned_df["city"] == "bangkok"]["price"]
bangkok_usd = bangkok_price*0.029

# hong kong price 
hongkong_price = cleaned_df.loc[cleaned_df["city"] == "hongkong"]["price"]
hongkong_usd = hongkong_price*0.13

# singapore price 
singapore_price = cleaned_df.loc[cleaned_df["city"] == "singapore"]["price"]
singapore_usd = singapore_price*0.75

In [161]:
london_price

0         79.0
1         75.0
3        132.0
4         65.0
5        425.0
         ...
71242     69.0
71280     65.0
71346    176.0
71369    141.0
71376    324.0
Name: price, Length: 20943, dtype: float64

In [162]:
london_usd

0         97.96
1         93.00
3        163.68
4         80.60
5        527.00
          ...
71242     85.56
71280     80.60
71346    218.24
71369    174.84
71376    401.76
Name: price, Length: 20943, dtype: float64